Repository openwisp/netjsongraph.js, pull requests merged in 2025-08, with the labels that each got.

#349 [feature] Added Cluster Prevention Mechanism #171
  README.md
  public/assets/data/netjson-clustering.json
  public/example_templates/netjson-clustering.html
  src/js/netjsongraph.config.js
  src/js/netjsongraph.core.js
  src/js/netjsongraph.geojson.js
  src/js/netjsongraph.render.js
  src/js/netjsongraph.util.js
  test/netjsongraph.config.test.js
  test/netjsongraph.render.test.js
  test/netjsongraph.spec.js
  test/netjsongraph.util.test.js
Labels: enhancement

#407 [fix] Enhance label styling in NetJSONGraph config
  public/assets/data/netjsonmap.json
  src/js/netjsongraph.config.js
  src/js/netjsongraph.render.js
  test/netjsongraph.spec.js
Labels: enhancement, gsoc-idea

#424 [deps] Fixed prettier version in package.json and yarn.lock
  package.json
  yarn.lock
Labels: bug
